version: "3.9"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api_prod
    hostname: api_prod
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=production
    networks:
      - iab330_Harry
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: client_prod
    hostname: client_prod
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./client/src:/app/src
      - "/app/node_modules"
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
    networks:
      - iab330_Harry
networks:
  iab330_Harry:
    external: true
