version: "3.9"
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    hostname: server
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - './server:/app'
      - '/app/node_modules'
    networks:
      - iab330_Harry
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: client_prod
    hostname: client_prod
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - '/app/node_modules'
    enviroment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
    networks:
      - iab330_Harry
networks:
  iab330_Harry:
    external: true
